apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}
      {{- if eq .Values.frontendService.type "NodePort" }}
      nodePort: {{ .Values.frontendService.nodePort }}
      {{- end }}
